#!/bin/bash
# Tool Factory — Hook Generator
# Generates a Claude Code hook script and registers it in settings.json.
#
# Usage: ./hook.sh "hook-name" "One-line description" [event]
# Example: ./hook.sh "lint-on-save" "Run ESLint after file writes" PostToolUse
#
# Events: SessionStart | SessionEnd | Notification | Stop | PostToolUse
#
# Output: ~/.claude/hooks/<hook-name>.sh (executable)
#         Registers in ~/.claude/settings.json hooks section
#         Updates tool-factory/registry/index.json

set -euo pipefail

# --- Config ---
HOOKS_DIR="$HOME/.claude/hooks"
SETTINGS="$HOME/.claude/settings.json"
FACTORY_DIR="$HOME/Development/id8/tool-factory"
REGISTRY="$FACTORY_DIR/registry/index.json"
FIXTURES_DIR="$FACTORY_DIR/range/fixtures"

# --- Colors ---
ORANGE='\033[38;2;239;111;46m'
TEAL='\033[38;2;78;205;196m'
AMBER='\033[38;2;245;158;11m'
RED='\033[38;2;239;68;68m'
GREEN='\033[38;2;34;197;94m'
GRAY='\033[38;2;119;119;119m'
WHITE='\033[38;2;238;238;238m'
RESET='\033[0m'

# --- Input Validation ---
if [ $# -lt 2 ]; then
  echo -e "${RED}Usage: ./hook.sh \"hook-name\" \"One-line description\" [event]${RESET}"
  echo -e "${GRAY}Events: SessionStart | SessionEnd | Notification | Stop | PostToolUse${RESET}"
  exit 1
fi

HOOK_NAME="$1"
HOOK_DESC="$2"
HOOK_EVENT="${3:-PostToolUse}"

# Validate name (kebab-case)
if ! echo "$HOOK_NAME" | grep -qE '^[a-z][a-z0-9-]*$'; then
  echo -e "${RED}Hook name must be kebab-case (e.g., lint-on-save)${RESET}"
  exit 1
fi

# Validate event
case "$HOOK_EVENT" in
  SessionStart|SessionEnd|Notification|Stop|PostToolUse) ;;
  *) echo -e "${RED}Event must be: SessionStart | SessionEnd | Notification | Stop | PostToolUse${RESET}"; exit 1 ;;
esac

# Check for duplicates
HOOK_FILE="$HOOKS_DIR/$HOOK_NAME.sh"
if [ -f "$HOOK_FILE" ]; then
  echo -e "${AMBER}Warning: Hook '$HOOK_NAME' already exists at $HOOK_FILE${RESET}"
  exit 1
fi

echo -e "${ORANGE}Tool Factory${RESET} ${WHITE}— Generating hook: $HOOK_NAME${RESET}"
echo ""

# --- Generate Hook Script ---
mkdir -p "$HOOKS_DIR"

cat > "$HOOK_FILE" << 'HOOK_HEADER'
#!/bin/bash
HOOK_HEADER

cat >> "$HOOK_FILE" << HOOK_EOF
# $HOOK_NAME — $HOOK_DESC
# Event: $HOOK_EVENT
# Generated by Tool Factory on $(date +%Y-%m-%d)
#
# Input: Read from stdin (JSON) or environment variables
# Output: Echo messages to stderr, exit code determines pass/fail
#   exit 0 = success (continue)
#   exit 1 = failure (block action)

set -euo pipefail

# --- Read Input ---
# For PostToolUse hooks, input comes as JSON on stdin:
#   { "tool_name": "Write", "tool_input": { "file_path": "..." }, "tool_output": "..." }
# For other hooks, use environment variables.

INPUT=""
if [ ! -t 0 ]; then
  INPUT=\$(cat)
fi

# --- Core Logic ---
# TODO: Implement hook logic here
#
# Example patterns:
#   TOOL_NAME=\$(echo "\$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_name',''))" 2>/dev/null || echo "")
#   FILE_PATH=\$(echo "\$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_input',{}).get('file_path',''))" 2>/dev/null || echo "")

echo "[hook:$HOOK_NAME] Running..." >&2

# --- Report ---
# echo "[hook:$HOOK_NAME] Result: PASS" >&2
exit 0
HOOK_EOF

chmod +x "$HOOK_FILE"
echo -e "  ${GREEN}Created${RESET} $HOOK_FILE (executable)"

# --- Register in settings.json ---
if [ -f "$SETTINGS" ]; then
  python3 << PYEOF
import json

with open('$SETTINGS', 'r') as f:
    settings = json.load(f)

if 'hooks' not in settings:
    settings['hooks'] = {}

event = '$HOOK_EVENT'
if event not in settings['hooks']:
    settings['hooks'][event] = []

# Check if already registered
hook_cmd = '/bin/bash "$HOME/.claude/hooks/$HOOK_NAME.sh"'
already = any(
    any(h.get('command', '').endswith('$HOOK_NAME.sh"') or h.get('command', '').endswith("$HOOK_NAME.sh'")
        for h in entry.get('hooks', []))
    for entry in settings['hooks'][event]
)

if not already:
    settings['hooks'][event].append({
        "matcher": "",
        "hooks": [
            {
                "type": "command",
                "command": hook_cmd,
                "timeout": 10
            }
        ]
    })
    with open('$SETTINGS', 'w') as f:
        json.dump(settings, f, indent=2)
    print("Registered in settings.json")
else:
    print("Already registered in settings.json")
PYEOF
  echo -e "  ${GREEN}Registered${RESET} in settings.json -> hooks.$HOOK_EVENT"
else
  echo -e "  ${AMBER}Warning${RESET} settings.json not found — register manually"
fi

# --- Generate Test Fixture ---
mkdir -p "$FIXTURES_DIR"

cat > "$FIXTURES_DIR/hook-$HOOK_NAME.json" << FIXTURE_EOF
{
  "tool": "$HOOK_NAME",
  "type": "hook",
  "created": "$(date +%Y-%m-%d)",
  "intake": {
    "problem": "$HOOK_DESC",
    "event": "$HOOK_EVENT"
  },
  "tests": [
    {
      "name": "exit_code_zero",
      "type": "unit",
      "command": "echo '{}' | bash $HOOK_FILE",
      "expected": "Exit code 0",
      "status": "pending"
    },
    {
      "name": "handles_empty_input",
      "type": "edge_case",
      "command": "echo '' | bash $HOOK_FILE",
      "expected": "Graceful handling, exit 0",
      "status": "pending"
    }
  ],
  "scorecard": {
    "score": null,
    "tests_passed": 0,
    "tests_failed": 0,
    "recommendation": null,
    "last_run": null
  }
}
FIXTURE_EOF

echo -e "  ${GREEN}Created${RESET} $FIXTURES_DIR/hook-$HOOK_NAME.json"

# --- Update Registry ---
if [ -f "$REGISTRY" ]; then
  python3 << PYEOF
import json

with open('$REGISTRY', 'r') as f:
    registry = json.load(f)

new_hook = {
    "name": "$HOOK_NAME",
    "type": "hook",
    "purpose": "$HOOK_DESC",
    "event": "$HOOK_EVENT",
    "status": "born",
    "created": "$(date +%Y-%m-%d)",
    "last_used": None,
    "factory_generated": True
}

existing = [h for h in registry.get('hooks', []) if h['name'] == '$HOOK_NAME']
if not existing:
    if 'hooks' not in registry:
        registry['hooks'] = []
    registry['hooks'].append(new_hook)
    registry['meta']['total_tools'] = registry['meta']['total_tools'] + 1
    registry['meta']['counts']['hooks'] = registry['meta']['counts']['hooks'] + 1

with open('$REGISTRY', 'w') as f:
    json.dump(registry, f, indent=2, default=str)

print("Registry updated")
PYEOF
  echo -e "  ${GREEN}Updated${RESET} registry/index.json"
fi

# --- Summary ---
echo ""
echo -e "${ORANGE}────────────────────────────────────────${RESET}"
echo -e "${WHITE}Hook generated: $HOOK_NAME${RESET}"
echo -e "${GRAY}Location:  $HOOK_FILE${RESET}"
echo -e "${GRAY}Event:     $HOOK_EVENT${RESET}"
echo -e "${GRAY}Status:    BORN (implement logic in TODO section)${RESET}"
echo -e "${GRAY}Test:      echo '{}' | bash $HOOK_FILE${RESET}"
echo -e "${ORANGE}────────────────────────────────────────${RESET}"
